"""baseline schema

Skema lengkap aplikasi per PR #1 (state paper trading berbasis database).

Database yang SUDAH ada (dibuat lewat init_db / create_all) cukup ditandai:
    alembic stamp 0001_baseline
Database baru:
    alembic upgrade head

Revision ID: 0001_baseline
Revises:
Create Date: 2026-09-24 21:39:46.710642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_baseline'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_resolutions',
    sa.Column('market_id', sa.String(length=255), nullable=False),
    sa.Column('market_name', sa.String(length=512), nullable=True),
    sa.Column('winning_outcome', sa.String(length=20), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('market_id')
    )
    op.create_table('market_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('market_id', sa.String(length=255), nullable=False),
    sa.Column('market_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolution_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('price_yes', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('price_no', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_market_snapshots_category', 'market_snapshots', ['category'], unique=False)
    op.create_index('idx_market_snapshots_market_id', 'market_snapshots', ['market_id'], unique=False)
    op.create_index('idx_market_snapshots_market_ts', 'market_snapshots', ['market_id', 'timestamp'], unique=False)
    op.create_index('idx_market_snapshots_status', 'market_snapshots', ['status'], unique=False)
    op.create_index('idx_market_snapshots_timestamp', 'market_snapshots', ['timestamp'], unique=False)
    op.create_table('paper_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('initial_balance', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('unrealized_pnl', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('total_fees', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('current_balance >= 0', name='chk_accounts_current_balance'),
    sa.CheckConstraint('initial_balance >= 0', name='chk_accounts_initial_balance'),
    sa.CheckConstraint('total_fees >= 0', name='chk_accounts_total_fees'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paper_cash_movements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='chk_cash_movements_amount'),
    sa.ForeignKeyConstraint(['account_id'], ['paper_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cash_movements_account_id', 'paper_cash_movements', ['account_id'], unique=False)
    op.create_table('paper_orders',
    sa.Column('paper_order_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('market_id', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', 'YES', 'NO', name='trade_side'), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('position_size', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('shares', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'PENDING', 'FILLED', 'CANCELLED', 'REJECTED', name='paper_order_status'), nullable=False),
    sa.Column('strategy_version', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('entry_price >= 0', name='chk_orders_entry_price'),
    sa.CheckConstraint('position_size >= 0', name='chk_orders_position_size'),
    sa.CheckConstraint('shares >= 0', name='chk_orders_shares'),
    sa.ForeignKeyConstraint(['account_id'], ['paper_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('paper_order_id')
    )
    op.create_index('idx_paper_orders_account_id', 'paper_orders', ['account_id'], unique=False)
    op.create_table('paper_positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('market_id', sa.String(length=255), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', 'YES', 'NO', name='trade_side'), nullable=False),
    sa.Column('shares', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('average_entry_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('position_size', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('unrealized_pnl', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('market_name', sa.String(length=512), nullable=True),
    sa.Column('strategy_version', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('average_entry_price >= 0', name='chk_positions_avg_entry'),
    sa.CheckConstraint('position_size >= 0', name='chk_positions_size'),
    sa.CheckConstraint('shares >= 0', name='chk_positions_shares'),
    sa.ForeignKeyConstraint(['account_id'], ['paper_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'market_id', 'side', name='uq_positions_account_market_side')
    )
    op.create_table('paper_trades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('market_id', sa.String(length=255), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', 'YES', 'NO', name='trade_side'), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('position_size', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('shares', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('gross_pnl', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('fees', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('net_pnl', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'WON', 'LOST', 'CANCELLED', 'CLOSED', name='paper_trade_status'), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('strategy_version', sa.String(length=100), nullable=False),
    sa.Column('market_name', sa.String(length=512), nullable=True),
    sa.CheckConstraint('entry_price >= 0', name='chk_trades_entry_price'),
    sa.CheckConstraint('exit_price >= 0', name='chk_trades_exit_price'),
    sa.CheckConstraint('fees >= 0', name='chk_trades_fees'),
    sa.CheckConstraint('position_size >= 0', name='chk_trades_position_size'),
    sa.CheckConstraint('shares >= 0', name='chk_trades_shares'),
    sa.ForeignKeyConstraint(['account_id'], ['paper_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trades_account_strategy', 'paper_trades', ['account_id', 'strategy_version'], unique=False)
    op.create_index('idx_trades_opened_at', 'paper_trades', ['opened_at'], unique=False)
    op.create_index('idx_trades_status', 'paper_trades', ['status'], unique=False)
    op.create_table('paper_balance_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('trade_id', sa.UUID(), nullable=True),
    sa.Column('balance', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('equity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('balance >= 0', name='chk_snapshots_balance'),
    sa.ForeignKeyConstraint(['account_id'], ['paper_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trade_id'], ['paper_trades.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paper_balance_snapshots')
    op.drop_index('idx_trades_status', table_name='paper_trades')
    op.drop_index('idx_trades_opened_at', table_name='paper_trades')
    op.drop_index('idx_trades_account_strategy', table_name='paper_trades')
    op.drop_table('paper_trades')
    op.drop_table('paper_positions')
    op.drop_index('idx_paper_orders_account_id', table_name='paper_orders')
    op.drop_table('paper_orders')
    op.drop_index('idx_cash_movements_account_id', table_name='paper_cash_movements')
    op.drop_table('paper_cash_movements')
    op.drop_table('paper_accounts')
    op.drop_index('idx_market_snapshots_timestamp', table_name='market_snapshots')
    op.drop_index('idx_market_snapshots_status', table_name='market_snapshots')
    op.drop_index('idx_market_snapshots_market_ts', table_name='market_snapshots')
    op.drop_index('idx_market_snapshots_market_id', table_name='market_snapshots')
    op.drop_index('idx_market_snapshots_category', table_name='market_snapshots')
    op.drop_table('market_snapshots')
    op.drop_table('market_resolutions')
    # ### end Alembic commands ###
    # Tipe ENUM native PostgreSQL tidak ikut terhapus bersama tabel
    if op.get_bind().dialect.name == "postgresql":
        for enum_name in ("paper_trade_status", "paper_order_status", "trade_side"):
            op.execute(f"DROP TYPE IF EXISTS {enum_name}")
