"""market latest

Tabel market_latest (satu baris per market) untuk pembacaan harga terkini tanpa memindai
histori market_snapshots. Diisi (backfill) dari snapshot terbaru setiap market.

Revision ID: 0002_market_latest
Revises: 0001_baseline
Create Date: 2026-09-24 22:00:26.166032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002_market_latest'
down_revision: Union[str, Sequence[str], None] = '0001_baseline'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

BACKFILL_SQL = """
INSERT INTO market_latest (
    market_id, market_name, status, is_resolved, resolution_time, end_date,
    price_yes, price_no, current_price, category, timestamp, last_snapshot_at
)
SELECT market_id, market_name, status, is_resolved, resolution_time, end_date,
       price_yes, price_no, current_price, category, timestamp, timestamp
FROM (
    SELECT s.*, ROW_NUMBER() OVER (PARTITION BY market_id ORDER BY timestamp DESC) AS rn
    FROM market_snapshots s
) latest
WHERE rn = 1
"""


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_latest',
    sa.Column('market_id', sa.String(length=255), nullable=False),
    sa.Column('market_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolution_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('price_yes', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('price_no', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_snapshot_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('market_id')
    )
    op.create_index('idx_market_latest_resolution_time', 'market_latest', ['resolution_time'], unique=False)
    op.create_index('idx_market_latest_resolved', 'market_latest', ['is_resolved'], unique=False)
    op.execute(BACKFILL_SQL)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_market_latest_resolved', table_name='market_latest')
    op.drop_index('idx_market_latest_resolution_time', table_name='market_latest')
    op.drop_table('market_latest')
    # ### end Alembic commands ###
