"""outcome labels

Nama asli outcome (mis. "Yes"/"No" atau "Up"/"Down") yang dipetakan ke sisi YES / NO.

Revision ID: 0003_outcome_labels
Revises: 0002_market_latest
Create Date: 2026-09-24 22:09:42.679949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003_outcome_labels'
down_revision: Union[str, Sequence[str], None] = '0002_market_latest'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_latest', sa.Column('outcome_yes_label', sa.String(length=50), nullable=True))
    op.add_column('market_latest', sa.Column('outcome_no_label', sa.String(length=50), nullable=True))
    op.add_column('market_snapshots', sa.Column('outcome_yes_label', sa.String(length=50), nullable=True))
    op.add_column('market_snapshots', sa.Column('outcome_no_label', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market_snapshots', 'outcome_no_label')
    op.drop_column('market_snapshots', 'outcome_yes_label')
    op.drop_column('market_latest', 'outcome_no_label')
    op.drop_column('market_latest', 'outcome_yes_label')
    # ### end Alembic commands ###
