"""recommendation alerts

Event rekomendasi yang sudah dikirim ke Telegram (mencegah notifikasi ganda).

Revision ID: 0004_recommendation_alerts
Revises: 0003_outcome_labels
Create Date: 2026-09-26 09:22:41.560992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004_recommendation_alerts'
down_revision: Union[str, Sequence[str], None] = '0003_outcome_labels'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation_alerts',
    sa.Column('event_key', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('local_date', sa.String(length=10), nullable=False),
    sa.Column('market_id', sa.String(length=255), nullable=True),
    sa.Column('price_yes', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('event_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommendation_alerts')
    # ### end Alembic commands ###
